version: 2
jobs:
  build:
    docker:
      - image: php:7.0-apache
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: |
            apt-get update && apt-get -y install zip
            apt-get --quiet install --yes python-pip
            pip install -U pip
            pip install awscli
      - run:
          name: zip code
          command: | 
            zip -r source-cnx.zip .
      - run:
          name: Upload code to S3
          command: aws s3 cp source-cnx.zip s3://codedeploy-cnx/cnx.zip
      - deploy:
          name: Execute CodeDeploy
          command: aws deploy create-deployment --application-name cnx_deploy --deployment-group-name cnx_deploy --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=codedeploy-cnx,bundleType=zip,key=cnx.zip --region ap-southeast-1
